apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-tracker-app
  namespace: portfolio-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-tracker-app
  template:
    metadata:
      labels:
        app: portfolio-tracker-app
    spec:
      containers:
      - name: app
        image: your-registry/portfolio-tracker:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: mongodb-uri
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: REDIS_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: jwt-secret
        - name: ALPHA_VANTAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: alpha-vantage-key
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: email-password
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: google-client-secret
        - name: EMAIL_FROM
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: EMAIL_FROM
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: EMAIL_HOST
        - name: EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: EMAIL_PORT
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: portfolio-config
              key: FRONTEND_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-tracker-service
  namespace: portfolio-tracker
spec:
  selector:
    app: portfolio-tracker-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-tracker-ingress
  namespace: portfolio-tracker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "portfolio-tracker-service"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.portfolio-tracker.com
    secretName: portfolio-tracker-tls
  rules:
  - host: api.portfolio-tracker.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-tracker-service
            port:
              number: 80