apiVersion: v1
kind: Namespace
metadata:
  name: portfolio-tracker
  labels:
    name: portfolio-tracker
---
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio-tracker
type: Opaque
data:
  # Base64 encoded values
  # Use: echo -n "your-secret" | base64
  mongodb-uri: bW9uZ29kYjovL21vbmdvLWRiLXNlcnZpY2U6MjcwMTcvcG9ydGZvbGlvX3RyYWNrZXI=
  jwt-secret: c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX3Byb2R1Y3Rpb24=
  alpha-vantage-key: eW91cl9hbHBoYV92YW50YWdlX2FwaV9rZXk=
  email-password: eW91cl9lbWFpbF9wYXNzd29yZA==
  google-client-id: eW91cl9nb29nbGVfY2xpZW50X2lk
  google-client-secret: eW91cl9nb29nbGVfY2xpZW50X3NlY3JldA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio-tracker
data:
  NODE_ENV: "production"
  PORT: "5000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  EMAIL_FROM: "noreply@portfolio-tracker.com"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_SECURE: "false"
  GOOGLE_CALLBACK_URL: "https://your-domain.com/api/v1/auth/google/callback"
  FRONTEND_URL: "https://your-frontend-domain.com"
  API_VERSION: "v1"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  CACHE_TTL: "300"
  SOCKET_CORS_ORIGIN: "https://your-frontend-domain.com"